### ISSUE TITLE
Documentation on how to create a test environment

### ISSUE THREAD

**Issue by hluaces** [oscarmlage/bofhers#27]
Right now testing changes for the app is quite painful because:

* There is no easy way to do it.
* Even if you deploy local services, there's no documentation on how to set up the application.
* There's also no documentation on how to set up Telegram's integration.

Ideally it should be as easy as "fill a configuration file" and "click a button" so that making changes is less painful both for new and veteran contributors.

**Comment by oscarmlage** [comment]
#28 Merged, thanks for the effort!
