### ISSUE TITLE
Show list of channels in the front page

### ISSUE THREAD

**Issue by oscarmlage** [oscarmlage/bofhers#36]

**Comment by MarcosBL** [comment]
No me da la vida pa PR pero al menos:

[public.zip](https://github.com/oscarmlage/bofhers/files/6230200/public.zip)

**Comment by oscarmlage** [comment]
> No me da la vida pa PR pero al menos:
> 
> [public.zip](https://github.com/oscarmlage/bofhers/files/6230200/public.zip)

Yo me encargo, ¡thanks @MarcosBL!

**Comment by pniaps** [comment]
A ver si puedo yo...
