### ISSUE TITLE
Add ruskifilter

### ISSUE THREAD

**Issue by Valkrieg** [oscarmlage/bofhers#6]
Every time user @alexandernst says something with specific terminations (previously analyzed) trigger `proteo_plancha_amif.png` sticker.

**Comment by alexandernst** [comment]
this is plain bullshit

**Comment by Valkrieg** [comment]
> this is plain bullshit
The one I have here hanging.

**Comment by alexandernst** [comment]
se te esta hanging porque ese computer is a piece of mierda pinchá en un palo

**Comment by macklus** [comment]
At least, its not too much expensive as an apple shit pc one

**Comment by alexandernst** [comment]
> At least, its not too much expensive as an apple shit pc one

toma, para que puedas sacarte your aws premium solutions knob certificate: https://www.youtube.com/watch?v=7Oox5ZcJQ7o

**Comment by macklus** [comment]
Ya la tengo, y aprendí cosas muy interesantes como separar cada cosa en su VPC, o usar cross accounts por seguridad... vamos, aprendí a hacer lo contrario de todo lo que haces tú
